### ISSUE TITLE
Admin is not opening on custom url in local 

### ISSUE THREAD

**Issue by Dhruv7298** [ManiruzzamanAkash/LaraCMS#5]
When i run php artisan serve it works but when I'm setting up custom url laracms.dev that time it's showing 404, Can you pls help me to solve

**Comment by ManiruzzamanAkash** [comment]
Hi @Dhruv7298, it's the common thing to go that way. It's the common thing for every Laravel application.
You have to do that on your server when you deploy website.

There are several approaches - 
1. Remove public from URL using .htaccess. OR,
2. Remove public from URL using updating Document root URL pointing to /public.

I'm closing this.
